export enum AppRoutes {
    signUp = 'sign-up',
    login = 'login',
    boards = 'boards',
    home = 'home',
    board = 'board',
    settings = 'settings'
}

export enum Messages {
    connect = 'connect',
    connectError = 'connect_error',
    disconnect = 'disconnect',
    sendMessage = 'send_message',
    createRoom = 'create_room',
    deleteCard = 'delete_card',
    deleteCarditem = 'delete_carditem',
    deleteColumn = 'delete_column',
    deleteFile = 'delete_file',
    getCard = 'get_card',
    getCarditem = 'get_carditem',
    getCarditems = 'get_carditems',
    getCards = 'get_cards',
    getColumn = 'get_column',
    getColumns = 'get_columns',
    getFile = 'get_file',
    getFiles = 'get_files',
    hello = 'hello',
    newCard = 'new_card',
    newCarditem = 'new_carditem',
    newColumn = 'new_column',
    newFile = 'new_file',
    updateCard = 'update_card',
    updateColumn = 'update_column',
    updateCarditem = 'update_carditem',
    getAtivityByUser = 'get_AtivityByUser',
    getAtivityByBoard = 'get_AtivityByBoard',
    newInvite = 'new_invite',
    checkInvitesByEmail = 'check_invitesbyemail',
    getUsersToBoards = 'get_userstoboards',
    deleteUsersToBoards = 'delete_userstoboards'
}
